### ISSUE TITLE
needs clarifications

### ISSUE THREAD

**Issue by noahzn** [pladosz/AI_deck_vel_send_cpx#1]
Hi @pladosz, thank you for sharing the code. I have some questions regarding the code.
1. If I understand correctly the code is modified based on the wifi-streamer, and it directly sends some velocity commands to control the Crazyflie. Is it correct? Where is the code for the Crazyflie to receive the data and fly according to the commands?
2. Have you tried to implement it using the app layer?

**Comment by pladosz** [comment]
Hi Noahzn,

please see replies to your questions:
1. yes your understanding is correct. What we do in essence is sending CRTP message format over CPX. Crazyflie knows how to handle it and automatically interprets it as velocity commands, so no need for extra code needed on the Crazyflie.

2. Just to clarify I understand your question as: whether I tried sending velocity commands from AI-deck to the app layer using CPX and then from app layer to the Crazyflie. I have never tried that although to the best of my knowledge that should be possible. I can get you started with two tips

- specify  the route  CPX_F_APP instead of CPX_F_SYSTEM in `cpxInitRoute(CPX_T_GAP8, CPX_T_STM32, CPX_F_SYSTEM, &txp.route)`. 

- you should write the app to receive your message on the app layer, you can use wi-fi-image-streamer example to see how to receive a CPX message. Note that you have to define your message structure inside the app as well.

I hope this helps!

**Comment by noahzn** [comment]
Thank you for your answers!! I didn't know that the Crazyflie could automatically respond to commands sent to "CPX_F_SYSTEM". Did you define the message type `(createVelMsgPacket)` according to any documentation? I only want to change the yaw rate.

What I was trying to do is exactly what you said, receive the message in the application layer and then set the yaw rate. But now that we can send commands directly to CPX_F_SYSTEM, which way do you think is better for controlling the drone from the AI deck? Must we send commands at about 10 Hz to keep the motor working if the `CPXFunction_t` is set to `CPX_F_SYSTEM`? I ask this because I remember that someone told you this in the discussion, but my concern is that I can only send commands at about 1 command per second.

**Comment by pladosz** [comment]
Hi,
Unfortunately, there is not any single documentation on how to do `createVelMsgPacket` as far as I understood it. I did it based on [https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/functional-areas/crtp/](url) and example from python shared with me in this discussion [https://github.com/orgs/bitcraze/discussions/519#discussioncomment-4726032](url). so you need to control just yaw while crazyflie keeps constant position?

As far as I know 10 Hz is the requirement. if your algorithm only generates 1 command per second, you can keep generated command and send the same command repeatedly to achieve 10 Hz?

I think nowadays my preferred method would be to send the command to app first, it gives you a lot more flexibility in terms of how to handle communication delays and safety. But I am not full decided on either of them. Although I have not fully tried this approach yet

**Comment by noahzn** [comment]
Hi,
"so you need to control just yaw while crazyflie keeps constant position?" It should continue to move forward slowly.
"if your algorithm only generates 1 command per second, you can keep generated command and send the same command repeatedly to achieve 10 Hz?" It is in a while loop, something like this: `capture an image; process the camera image at about 1 frame per second and output a yaw number; send the number to the app layer or stm32 to control the drone.` So, the 10 Hz cannot be guaranteed. I will ask them if using the app layer can get rid of the 10 Hz requirement.

Thank you again for your detailed reply!
